### PR TITLE
Make intent reseting optional with a preference

### PR DESCRIPTION
**Pull request by galexandrov**
Hi @EddyVerbruggen your fix will work but only for live environment, but for our other environments will not.
Do you have any concerns about this fix?

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hey @galexandrov, I have a few questions if you don't mind:

- Which other LiveSync backend servers are there? Are they all at .telerik.com perhaps?
- Do you intend the Telerik fork to include the `config.xml` preference (the upstream doesn't need it)?

**Comment by galexandrov** [comment]
Hey @EddyVerbruggen we have few environments, but they have different URLs for example sit-platform.telerik.rocks, testtap.telerik.com.
But the preference is not needed in the config.xml file it will work if it's set only

**Comment by EddyVerbruggen** [comment]
So it makes sense to include the preference on this fork, but not add it to the upstream repo, right? I'll merge and release this later today, thx!

**Comment by galexandrov** [comment]
I have removed the preference from the config.xml, because it's optional, but maybe we can mention it in the docs

**Comment by EddyVerbruggen** [comment]
Perhaps that's the best solution, I will add a big fat LiveSync note at the top!

**Comment by EddyVerbruggen** [comment]
v4.1.4 is now released. Thx!

**Pull request merged**
