### PR TITLE
Do not overwrite the intent, because other activities can use it

### PR DESCRIPTION
**Pull request by galexandrov**
LiveSync Plugin uses intent to receive the livesync url. 
But if Custom-URL-scheme plugin is included and it's loaded first the livesync plugin will receive intent with empty data

Is there a specific reason to set the intent data to NULL?

### CODE REVIEW

**Comment by galexandrov** [comment]
ping @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Hey @galexandrov, thanks for the PR!

Let me explain why that `setData(null)` is there:

The problem is with multi page apps (multiple html files), each with the `handleOpenURL` handler Javascript function (possibly included in a common js file), and you coldstart the app. In this case the intent will persist, so every page will get its `handleOpenURL` function invoked. I verified this behavior and it disappears again when nulling the intent.

Of course multi page apps can work around this issue programmatically, but it's a bit hard and probably breaks current usage.

Can you tell me more about the LiveSync intent so we can make this compatible without removing these lines? If there is something specific in the intent we can check that would help.

**Comment by galexandrov** [comment]
Hey @EddyVerbruggen in LiveSync plugin we override the onNewIntent to handle the intents as Custom-URL-scheme plugin.
The LiveSync use data intent to receive AB project URL for example icenium://platform.telerik.com/.....
I was wondering, can we make the intent cleaning optional and the default behavior will be as it is now.

**Comment by EddyVerbruggen** [comment]
I have no problem checking for something livesync specific in this plugin.

Will try to see if "platform.telerik.com" is part of the launching scheme. Shouldn't affect other usecases than LiveSync.

**Comment by EddyVerbruggen** [comment]
Hey @galexandrov, I've now release 4.1.3 which should be LiveSync compatible (tested it myself).

Cheers,
Eddy

**Pull request closed without merging**
